Docker-basics/basics-of-docker.md

Hey maintainers,
I have added a file which contains the basics of docker, why it came into being, and a brief history of it as well as some of its advantages. Do verify.

Added file containing basics of docker

---

Margin-vs-Padding/Blog.md

Do review it and accept it by adding Hacktoberfest-accepted label if you think everything is great.
Thank You.

Added an article on Margin vs padding

---

Infosys Interview Preparation Guide

it is all about Infosys interview preparation and please also practice some standard coding question for DSE & SP role

Infosys Interview preparation Guide

---

What is blockchain?

Hey @Adarsh-jaiss updated some examples to this v fascinating blog topic, hope you approve it :)

Update What is blockchain?

---

Interview Preparation - SQL, Python, Stats

Create Interview Preparation

---

CheatSheets/verilog.md

Added cheetsheet for verilog for hardware engineers

Added Verilog cheetsheet

---

HTML 101/HTML 101.md

Updated some of the lines with different words

Update HTML 101.md

---

Linux-Blog/Linux_Basics.md

Issue: #17 
Hey @Adarsh-jaiss, would you please review my PR?

added linux blog

---

README.md

Just a little typo error by me , now it is clean.
PLEASE merge!!

Update needed a little type error.

---

Data Structure and  Algorithm Cheatsheets.md

Added Create Data Structure and  Algorithm Cheatsheets.

Create Data Structure and  Algorithm Cheatsheets.md

---

Google maps/Crowdsourcing.md
Google maps/How-AI-helps-predict-traffic-and-determine-routes.md
Google maps/How-Do-Google-Maps-Know-About-Traffic-Conditions.md
Google maps/How-do-Google-Maps-know-about-current-traffic-conditions.md

Added a full documentation on how Google Maps track traffic in "Google maps" folder.

Added how Google Maps track traffic?

---

DevOps Resources/Computer Networking/how-does-https-work.md

Simple guide on how https work

Add how https work

---

Creative Resume Template/Resume.md
UIUX/UIUX Beginners Guide.md

Wrote an article about "Concepts and Key principles of User Experience design".

Created UIUX Beginners Guide.md

---

Competitive Programming guide/Guided Cp.md

This markdown file gives a better user experience and is filled with more resources and references from someone who is doing CP from quite a lot time.

Created Markdown File of CP Guide

---

Web Development/REST_API.md

Servse as a guide regarding designing of RESTful API

Adding REST_API documentation

---

CheatSheets/shortcut-keys-cheatsheet.md

I have completed the raised issue #14 
Please accept this PR as hacktoberfest contribution

Added Shortcut Keys Cheatsheet ( Issue #14)

---

A blog on BASH Scripting

Added A blog on BASH Scripting

---

CheatSheets/Dart_Cheat_Sheet.md

Cheat Sheet

---

LINUX/most used commands.md

Contributed towards creating most used commands in LINUX/UNIX.

Create most used commands.md

---

blog/markdown_html.md

I had added a blog in Markdown verses HTML.

Added a blog

---

CheatSheets/Google_Search_Shortcuts.md

Google Searching Shortcuts
Googling is a skill every developer should have, and narrowing the search results to find the exact thing you require is vital. This cheat sheet provides a guide to using some simple shortcuts to narrow down or broaden your search results and get the precise content you require.

New Cheatsheet added: Google Search Shortcuts

---

CheatSheets/React_Js_CheatSheet.md
Competitive Programming guide/Curated_Guide_CP.md

This is a beginner friendly ReactJS CheatSheet .
Also added a curated guide for competitive programming for beginners.
Kindly add this to Non code *** Hacktoberfest 2022 contribution list** label.
It would be really helpful.

ReactJs CheatSheet 2022

---

LINUX/Linux Cheatsheet

Look after my PR and let me know if there is any improvement required

I have added Linux Cheatsheet

---

CP and Related/Guide.txt

I added some of the points that I learned through my own experiences with Competitive Programming ... and which would prove to be quite useful tips for the beginners

Updated Guide.md and added some usefull stuff

---

Networking/Different Networking Protocols
Networking/Introduction to Networking and Data Flow
Networking/OSI Model

Hii,
I am Jyoti Rani with GitHub id- Jranii.
I want to contribute by adding one folder of networking.
Kindly consider it.
Thank you

Added one folder of Networking.

---

CheatSheets/Markdown_CheatSheet.md
CheatSheets/PythonCheatsheet.md
CheatSheets/linux-cheatsheet.md

Markdown cheatsheet

---

CheatSheets/PythonCheatsheet.md
CheatSheets/linux-cheatsheet.md
linuxcheatsheet.md

solved: #47
Add Linux cheatsheet with Markdown

Linux cheatsheet

---

UI Design Trends.md

Wrote an amazing blog to help understand the UI design Trends easily to everybody.

Create UI Design Trends.md

---

CheatSheets/Sql_CheatSheet.md

solved: #141
Add SQL Cheat Sheet with Markdown

Create Sql CheatSheet

---

Interview Preparation Notes/RoadMap to SDE

RoadMap to SDE

---

Frontend-Resources-main/README.md

Added more interview specific reources.

Updated Frontend resources

---

C++_Sort()_inner_implementation details/c++_sort_inner_implementation_details.md

I added the methods of sorting the vectors using just forward and backward iterators in ascending and descending orders respectively , i.e. without the use of greater<int>()

Added methods to sort in descending order using backward iterator

---

CheatSheets/Cpp.md

I added the output for the given code of min heap, added the code on how to create a min heap priority queue I also added alternate method to declare a pointer Updated information about some of the headers

Updated header info and added code of min heap priority queue

---

Interview Preparation Notes/Amazon Interview question

Added One of the most important interview questions

Create Amazon Interview question

---

Frontend-Resources-main/Frontend Developer RoadMap

its a simple frontend guide and i also mention some link where you can find some useful resources 
just enjoy it

Frontend developer RoadMap

---

Communication Skills/Roadmap

I am adding a Communication Skills Roadmap. Please look into my PR and let me know if there is any improvement required.

Communication Skills Roadmap

---

Interview Preparation Notes/Barclays_Preparation.md

I have added my preparation tips for Barclays' OA and interview.
Please merge it under hacktoberfest 2022
Thank you!

Added notes for issue192

---

DevOps Resources/Nginx/reverse-proxy-using-subdomains.md

A short tutorial about using NGINX as a reverse proxy with subdomains

Using NGINX as a reverse-proxy

---

Android Studio Very basic Guide/instruction.md

Could help some beginner while they are in their starting phase.

Basic andriod studio things

---

Interview Preparation Notes/JP_Morgan_CFG.md

I have added my CFG experience and tips and tricks for the same in this PR. Please merge it under Hacktober Fest 2022.
Thank You!

Added documentation for issue 191

---

Java/Language tools for Java
Web Development/JavaScript -Functions and Arrays

hello,
I'm Kumar Abhijeet , github id- kr84abhijeet
I've added notes about Javascript -Functions and Arrays in the repo
Kindly consider it 
Thank You

Created JavaScript -Functions and Arrays

---

Networking/DataLink_layer.md

Brief about the functions and structure of data link layer.

Added DataLink_layer in OSI model

---

CheatSheets/SQL Cheatsheet

SQL Cheatsheet

---

Bigdata_Intro/BigData_1.txt
Bigdata_Intro/BigData_2.txt
Bigdata_Intro/BigData_3.txt
Bigdata_Intro/BigData_4.txt
Bigdata_Intro/BigData_5.txt

Added 5 text files on BigData which covers the introduction to BigData analytics.

Added some notes on BigData introduction

---

Web Development/Frontend/Angular vs React.md

Created a Blog Angular vs React in Web development file

---

AI and ML/ML pipeline.md

outlined steps in building a predictive model

ML pipeline explained

---

CheatSheets/Git Cheat Sheet.md

Create Git Cheat Sheet.md

---

BlockChain and Crypto/Blockchain developer roadmap 2022

An ultimate guide on how to become a Blockchain Developer

 Blockchain developer roadmap 2022

---

Language, DSA and CP/Competitive Programming guide/Curated_Guide_CP.md

CSES, DMOJ link added along with description

added link to two new coding sites namely cses and DMOJ

---

UIUX/Typography.md

Please merge this @TKirtan under Hacktober Fest 2022. 
Thanks!

Added documentation for issue 290

---

Networking/Switching_Techniques.md

Three different computer network switching techniques: circuit, packet and message

added the switching techniques documentation in Networking

---

CheatSheets/Text Formating in HTML

Create Text Formating in HTML

---

OOP/cs50.md

added cs50 harvard university course which included basics of all programming languages

added cs50 harvard university course

---

Interview Questions

I have contributed by adding interview questions as a part of hactoberfest'22.

Create Interview Questions

---

Web Development/Frontend/Frontendintro

A basic introduction to front end Development.

Basic front end dev

---

AI and ML/What is AI

Update What is AI

---

Data Science

Data Science

---

Contributing.md

I noticed there is no contributing.md in this repo. So i am adding one to help those who are new to Open Source and Github. Please review my PR and merge it.

Adding Contributing.md
